# Generated by Django 2.2.2 on 2019-06-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190627_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categorie'},
        ),
    ]
